// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("company_master")]
public partial class CompanyMaster : AuditModels
{
    [Key]
    [Column("company_id")]
    public int CompanyId { get; set; }

    [Column("company_code", TypeName = "character varying")]
    public string CompanyCode { get; set; }

    [Column("company_name", TypeName = "character varying")]
    public string CompanyName { get; set; }

    [Column("sap_version", TypeName = "character varying")]
    public string SapVersion { get; set; }

    [Column("pr_allocation_logic", TypeName = "character varying")]
    public string PrAllocationLogic { get; set; }

    [Column("address", TypeName = "character varying")]
    public string Address { get; set; }

    [Column("company_logo_url", TypeName = "character varying")]
    public string CompanyLogoUrl { get; set; }

    [Column("company_logo_name", TypeName = "character varying")]
    public string CompanyLogoName { get; set; }

    [Column("sap_secretkey")] 
    public string SapSecretkey { get; set; }

    [Column("default_currency")]
    public string DefaultCurrency { get; set; } = "INR";

    [Column("qty_decimal_places")]
    public int QtyDecimalPlaces { get; set; } = 3;

    [Column("value_decimal_places")]
    public int ValueDecimalPlaces { get; set; } = 2;
    [Column("is_indian_currency")]
    public bool IsIndianCurrency { get; set; } = true;
    [Column("date_format")]
    public string DateFormat { get; set; } = "dd/MM/yyyy";

    [Column("time_format")]
    public string TimeFormat { get; set; } = "hh:mm tt";

    [Column("prno_prefix")]
    public string PRNo_Prefix { get; set; }

    [Column("prno_length")]
    public int? PrNo_Length { get; set; }

    [Column("rfq_prefix")]
    public string RFQPrefix { get; set; } = "R";
    [Column("rfq_length")]
    public int RFQLength { get; set; } = 4;

    [Column("auction_prefix")]
    public string AuctionPrefix { get; set; } = "A";
    [Column("auction_length")]
    public int AuctionLength { get; set; } = 4;

    [Column("supplier_group_prefix")]
    public string VendorGroupPrefix { get; set; } = "WCL";

    [Column("supplier_group_length")]
    public int VendorGroupLength { get; set; } = 7;

    [Column("suppliercode_prefix")]
    public string VendorCodePrefix { get; set; } = "T";

    [Column("suppliercode_length")]
    public int VendorCodeLength { get; set; } = 7;
    [Column("workflow_prefix")]
    public string WorkflowPrefix { get; set; } = "WF/";
    [Column("workflow_length")]
    public int WorkflowLength { get; set; } = 5;
    [Column("workflow_version_length")]
    public int WorkflowVersionLength { get; set; } = 3;

    [Column("time_zone")]
    public string? TimeZone { get; set; }

    [Column("time_country")]
    public string? TimeCountry { get; set; }
    [Column("participate_terms")]
    public string ParticipateTerms { get; set; } = "";

    [Column("nfa_prefix")]
    public string NFAPrefix { get; set; } = "";

    [Column("nfano_length")]
    public int NFALength { get; set; } = 6;

    [Column("po_months_validity")]
    public int PoMonthsValidity { get; set; } = 12;

    [Column("site_url")]
    public string SiteURL { get; set; } = "";

    // Navigation properties commented out - not needed for migration
    /*
    [InverseProperty("Company")]
    public virtual ICollection<ErpPrLine> ErpPrLines { get; set; } = new List<ErpPrLine>();

    [InverseProperty("Company")]
    public virtual ICollection<IncotermMaster> IncotermMasters { get; set; } = new List<IncotermMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<MaterialGroupMaster> MaterialGroupMasters { get; set; } = new List<MaterialGroupMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<MaterialMaster> MaterialMasters { get; set; } = new List<MaterialMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<PaymentTermMaster> PaymentTermMasters { get; set} = new List<PaymentTermMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<PlantMaster> PlantMasters { get; set; } = new List<PlantMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<PoConditionMaster> PoConditionMasters { get; set; } = new List<PoConditionMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<PoDocTypeMaster> PoDocTypeMasters { get; set; } = new List<PoDocTypeMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<PurchaseGroupMaster> PurchaseGroupMasters { get; set; } = new List<PurchaseGroupMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<PurchaseOrganizationMaster> PurchaseOrganizationMasters { get; set; } = new List<PurchaseOrganizationMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<TaxCodeMaster> TaxCodeMasters { get; set; } = new List<TaxCodeMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<UomMaster> UomMasters { get; set; } = new List<UomMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<EventMaster> EventMasters { get; set; } = new List<EventMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<UserCompanyMaster> UserCompanyMasters { get; set; } = new List<UserCompanyMaster>();

    [InverseProperty("Company")]
    public virtual ICollection<DynamicTableLabel> DynamicTableLabels { get; set; } = new List<DynamicTableLabel>();

    [InverseProperty("Company")]
    public virtual ICollection<FileValidationRule> FileValidationRules { get; set; } = new List<FileValidationRule>();

    [InverseProperty("Company")]
    public virtual ICollection<ErpCurrencyExchangeRate> ErpCurrencyExchangeRates { get; set; } = new List<ErpCurrencyExchangeRate>();
    */
}