// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SeedData.Models;

namespace SeedData.Models;

[Table("permission_group")]
[Index("PermissionGroupName", Name = "permission_group_permission_group_name_key", IsUnique = true)]
public partial class PermissionGroup : AuditModels
{
    [Key]
    [Column("permission_group_id")]
    public int PermissionGroupId { get; set; }

    [Required]
    [Column("permission_group_name")]
    [StringLength(100)]
    public string PermissionGroupName { get; set; }

    [Required]
    [Column("display_name")]
    [StringLength(150)]
    public string DisplayName { get; set; }

    [Column("icon")]
    [StringLength(100)]
    public string Icon { get; set; }

    [Column("order_index")]
    public int? OrderIndex { get; set; }

    [Column("is_active")]
    public bool? IsActive { get; set; } 

    [InverseProperty("PermissionGroup")]
    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}