// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("permissions")]
[Index("PermissionName", Name = "permissions_permission_name_key", IsUnique = true)]
public partial class Permission : AuditModels
{
    [Key]
    [Column("Permission_id")]
    public int PermissionId { get; set; }

    [Required]
    [Column("permission_name")]
    [StringLength(100)]
    public string PermissionName { get; set; }

    [Column("description")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("permission_group_id")]
    public int PermissionGroupId { get; set; }

    [ForeignKey("PermissionGroupId")]
    [InverseProperty("Permissions")]
    public virtual PermissionGroup PermissionGroup { get; set; }

    // Navigation properties commented out - not needed for migration
    /*
    [InverseProperty("Permission")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();

    [InverseProperty("Permission")]
    public virtual ICollection<UserPermission> UserPermissions { get; set; } = new List<UserPermission>();
    */
}