using Microsoft.EntityFrameworkCore;
using SeedData.Models;

namespace Seed
{
    public static class CountryMasterSeed
    {
        public static void SeedData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CountryMaster>(entity =>
            {
                entity.HasData(
                    new CountryMaster { CountryID = 1, CountryName = "Afghanistan", CountryCode = "AF" },
                    new CountryMaster { CountryID = 2, CountryName = "Albania", CountryCode = "AL" },
                    new CountryMaster { CountryID = 3, CountryName = "Algeria", CountryCode = "DZ" },
                    new CountryMaster { CountryID = 4, CountryName = "Andorra", CountryCode = "AD" },
                    new CountryMaster { CountryID = 5, CountryName = "Angola", CountryCode = "AO" },
                    new CountryMaster { CountryID = 6, CountryName = "Antigua and Barbuda", CountryCode = "AG" },
                    new CountryMaster { CountryID = 7, CountryName = "Argentina", CountryCode = "AR" },
                    new CountryMaster { CountryID = 8, CountryName = "Armenia", CountryCode = "AM" },
                    new CountryMaster { CountryID = 9, CountryName = "Australia", CountryCode = "AU" },
                    new CountryMaster { CountryID = 10, CountryName = "Austria", CountryCode = "AT" },
                    new CountryMaster { CountryID = 11, CountryName = "Azerbaijan", CountryCode = "AZ" },
                    new CountryMaster { CountryID = 12, CountryName = "Bahamas", CountryCode = "BS" },
                    new CountryMaster { CountryID = 13, CountryName = "Bahrain", CountryCode = "BH" },
                    new CountryMaster { CountryID = 14, CountryName = "Bangladesh", CountryCode = "BD" },
                    new CountryMaster { CountryID = 15, CountryName = "Barbados", CountryCode = "BB" },
                    new CountryMaster { CountryID = 16, CountryName = "Belarus", CountryCode = "BY" },
                    new CountryMaster { CountryID = 17, CountryName = "Belgium", CountryCode = "BE" },
                    new CountryMaster { CountryID = 18, CountryName = "Belize", CountryCode = "BZ" },
                    new CountryMaster { CountryID = 19, CountryName = "Benin", CountryCode = "BJ" },
                    new CountryMaster { CountryID = 20, CountryName = "Bhutan", CountryCode = "BT" },
                    new CountryMaster { CountryID = 21, CountryName = "Bolivia", CountryCode = "BO" },
                    new CountryMaster { CountryID = 22, CountryName = "Bosnia and Herzegovina", CountryCode = "BA" },
                    new CountryMaster { CountryID = 23, CountryName = "Botswana", CountryCode = "BW" },
                    new CountryMaster { CountryID = 24, CountryName = "Brazil", CountryCode = "BR" },
                    new CountryMaster { CountryID = 25, CountryName = "Brunei", CountryCode = "BN" },
                    new CountryMaster { CountryID = 26, CountryName = "Bulgaria", CountryCode = "BG" },
                    new CountryMaster { CountryID = 27, CountryName = "Burkina Faso", CountryCode = "BF" },
                    new CountryMaster { CountryID = 28, CountryName = "Burundi", CountryCode = "BI" },
                    new CountryMaster { CountryID = 29, CountryName = "Cabo Verde", CountryCode = "CV" },
                    new CountryMaster { CountryID = 30, CountryName = "Cambodia", CountryCode = "KH" },
                    new CountryMaster { CountryID = 31, CountryName = "Cameroon", CountryCode = "CM" },
                    new CountryMaster { CountryID = 32, CountryName = "Canada", CountryCode = "CA" },
                    new CountryMaster { CountryID = 33, CountryName = "Central African Republic", CountryCode = "CF" },
                    new CountryMaster { CountryID = 34, CountryName = "Chad", CountryCode = "TD" },
                    new CountryMaster { CountryID = 35, CountryName = "Chile", CountryCode = "CL" },
                    new CountryMaster { CountryID = 36, CountryName = "China", CountryCode = "CN" },
                    new CountryMaster { CountryID = 37, CountryName = "Colombia", CountryCode = "CO" },
                    new CountryMaster { CountryID = 38, CountryName = "Comoros", CountryCode = "KM" },
                    new CountryMaster { CountryID = 39, CountryName = "Congo, Democratic Republic of the", CountryCode = "CD" },
                    new CountryMaster { CountryID = 40, CountryName = "Congo, Republic of the", CountryCode = "CG" },
                    new CountryMaster { CountryID = 41, CountryName = "Costa Rica", CountryCode = "CR" },
                    new CountryMaster { CountryID = 42, CountryName = "Côte d'Ivoire", CountryCode = "CI" },
                    new CountryMaster { CountryID = 43, CountryName = "Croatia", CountryCode = "HR" },
                    new CountryMaster { CountryID = 44, CountryName = "Cuba", CountryCode = "CU" },
                    new CountryMaster { CountryID = 45, CountryName = "Cyprus", CountryCode = "CY" },
                    new CountryMaster { CountryID = 46, CountryName = "Czechia", CountryCode = "CZ" },
                    new CountryMaster { CountryID = 47, CountryName = "Denmark", CountryCode = "DK" },
                    new CountryMaster { CountryID = 48, CountryName = "Djibouti", CountryCode = "DJ" },
                    new CountryMaster { CountryID = 49, CountryName = "Dominica", CountryCode = "DM" },
                    new CountryMaster { CountryID = 50, CountryName = "Dominican Republic", CountryCode = "DO" },
                    new CountryMaster { CountryID = 51, CountryName = "Ecuador", CountryCode = "EC" },
                    new CountryMaster { CountryID = 52, CountryName = "Egypt", CountryCode = "EG" },
                    new CountryMaster { CountryID = 53, CountryName = "El Salvador", CountryCode = "SV" },
                    new CountryMaster { CountryID = 54, CountryName = "Equatorial Guinea", CountryCode = "GQ" },
                    new CountryMaster { CountryID = 55, CountryName = "Eritrea", CountryCode = "ER" },
                    new CountryMaster { CountryID = 56, CountryName = "Estonia", CountryCode = "EE" },
                    new CountryMaster { CountryID = 57, CountryName = "Eswatini", CountryCode = "SZ" },
                    new CountryMaster { CountryID = 58, CountryName = "Ethiopia", CountryCode = "ET" },
                    new CountryMaster { CountryID = 59, CountryName = "Fiji", CountryCode = "FJ" },
                    new CountryMaster { CountryID = 60, CountryName = "Finland", CountryCode = "FI" },
                    new CountryMaster { CountryID = 61, CountryName = "France", CountryCode = "FR" },
                    new CountryMaster { CountryID = 62, CountryName = "Gabon", CountryCode = "GA" },
                    new CountryMaster { CountryID = 63, CountryName = "Gambia", CountryCode = "GM" },
                    new CountryMaster { CountryID = 64, CountryName = "Georgia", CountryCode = "GE" },
                    new CountryMaster { CountryID = 65, CountryName = "Germany", CountryCode = "DE" },
                    new CountryMaster { CountryID = 66, CountryName = "Ghana", CountryCode = "GH" },
                    new CountryMaster { CountryID = 67, CountryName = "Greece", CountryCode = "GR" },
                    new CountryMaster { CountryID = 68, CountryName = "Grenada", CountryCode = "GD" },
                    new CountryMaster { CountryID = 69, CountryName = "Guatemala", CountryCode = "GT" },
                    new CountryMaster { CountryID = 70, CountryName = "Guinea", CountryCode = "GN" },
                    new CountryMaster { CountryID = 71, CountryName = "Guinea-Bissau", CountryCode = "GW" },
                    new CountryMaster { CountryID = 72, CountryName = "Guyana", CountryCode = "GY" },
                    new CountryMaster { CountryID = 73, CountryName = "Haiti", CountryCode = "HT" },
                    new CountryMaster { CountryID = 74, CountryName = "Honduras", CountryCode = "HN" },
                    new CountryMaster { CountryID = 75, CountryName = "Hungary", CountryCode = "HU" },
                    new CountryMaster { CountryID = 76, CountryName = "Iceland", CountryCode = "IS" },
                    new CountryMaster { CountryID = 77, CountryName = "India", CountryCode = "IN" },
                    new CountryMaster { CountryID = 78, CountryName = "Indonesia", CountryCode = "ID" },
                    new CountryMaster { CountryID = 79, CountryName = "Iran", CountryCode = "IR" },
                    new CountryMaster { CountryID = 80, CountryName = "Iraq", CountryCode = "IQ" },
                    new CountryMaster { CountryID = 81, CountryName = "Ireland", CountryCode = "IE" },
                    new CountryMaster { CountryID = 82, CountryName = "Israel", CountryCode = "IL" },
                    new CountryMaster { CountryID = 83, CountryName = "Italy", CountryCode = "IT" },
                    new CountryMaster { CountryID = 84, CountryName = "Jamaica", CountryCode = "JM" },
                    new CountryMaster { CountryID = 85, CountryName = "Japan", CountryCode = "JP" },
                    new CountryMaster { CountryID = 86, CountryName = "Jordan", CountryCode = "JO" },
                    new CountryMaster { CountryID = 87, CountryName = "Kazakhstan", CountryCode = "KZ" },
                    new CountryMaster { CountryID = 88, CountryName = "Kenya", CountryCode = "KE" },
                    new CountryMaster { CountryID = 89, CountryName = "Kiribati", CountryCode = "KI" },
                    new CountryMaster { CountryID = 90, CountryName = "Korea, North", CountryCode = "KP" },
                    new CountryMaster { CountryID = 91, CountryName = "Korea, South", CountryCode = "KR" },
                    new CountryMaster { CountryID = 92, CountryName = "Kosovo", CountryCode = "XK" },
                    new CountryMaster { CountryID = 93, CountryName = "Kuwait", CountryCode = "KW" },
                    new CountryMaster { CountryID = 94, CountryName = "Kyrgyzstan", CountryCode = "KG" },
                    new CountryMaster { CountryID = 95, CountryName = "Laos", CountryCode = "LA" },
                    new CountryMaster { CountryID = 96, CountryName = "Latvia", CountryCode = "LV" },
                    new CountryMaster { CountryID = 97, CountryName = "Lebanon", CountryCode = "LB" },
                    new CountryMaster { CountryID = 98, CountryName = "Lesotho", CountryCode = "LS" },
                    new CountryMaster { CountryID = 99, CountryName = "Liberia", CountryCode = "LR" },
                    new CountryMaster { CountryID = 100, CountryName = "Libya", CountryCode = "LY" },
                    new CountryMaster { CountryID = 101, CountryName = "Liechtenstein", CountryCode = "LI" },
                    new CountryMaster { CountryID = 102, CountryName = "Lithuania", CountryCode = "LT" },
                    new CountryMaster { CountryID = 103, CountryName = "Luxembourg", CountryCode = "LU" },
                    new CountryMaster { CountryID = 104, CountryName = "Madagascar", CountryCode = "MG" },
                    new CountryMaster { CountryID = 105, CountryName = "Malawi", CountryCode = "MW" },
                    new CountryMaster { CountryID = 106, CountryName = "Malaysia", CountryCode = "MY" },
                    new CountryMaster { CountryID = 107, CountryName = "Maldives", CountryCode = "MV" },
                    new CountryMaster { CountryID = 108, CountryName = "Mali", CountryCode = "ML" },
                    new CountryMaster { CountryID = 109, CountryName = "Malta", CountryCode = "MT" },
                    new CountryMaster { CountryID = 110, CountryName = "Marshall Islands", CountryCode = "MH" },
                    new CountryMaster { CountryID = 111, CountryName = "Mauritania", CountryCode = "MR" },
                    new CountryMaster { CountryID = 112, CountryName = "Mauritius", CountryCode = "MU" },
                    new CountryMaster { CountryID = 113, CountryName = "Mexico", CountryCode = "MX" },
                    new CountryMaster { CountryID = 114, CountryName = "Micronesia", CountryCode = "FM" },
                    new CountryMaster { CountryID = 115, CountryName = "Moldova", CountryCode = "MD" },
                    new CountryMaster { CountryID = 116, CountryName = "Monaco", CountryCode = "MC" },
                    new CountryMaster { CountryID = 117, CountryName = "Mongolia", CountryCode = "MN" },
                    new CountryMaster { CountryID = 118, CountryName = "Montenegro", CountryCode = "ME" },
                    new CountryMaster { CountryID = 119, CountryName = "Morocco", CountryCode = "MA" },
                    new CountryMaster { CountryID = 120, CountryName = "Mozambique", CountryCode = "MZ" },
                    new CountryMaster { CountryID = 121, CountryName = "Myanmar", CountryCode = "MM" },
                    new CountryMaster { CountryID = 122, CountryName = "Namibia", CountryCode = "NA" },
                    new CountryMaster { CountryID = 123, CountryName = "Nauru", CountryCode = "NR" },
                    new CountryMaster { CountryID = 124, CountryName = "Nepal", CountryCode = "NP" },
                    new CountryMaster { CountryID = 125, CountryName = "Netherlands", CountryCode = "NL" },
                    new CountryMaster { CountryID = 126, CountryName = "New Zealand", CountryCode = "NZ" },
                    new CountryMaster { CountryID = 127, CountryName = "Nicaragua", CountryCode = "NI" },
                    new CountryMaster { CountryID = 128, CountryName = "Niger", CountryCode = "NE" },
                    new CountryMaster { CountryID = 129, CountryName = "Nigeria", CountryCode = "NG" },
                    new CountryMaster { CountryID = 130, CountryName = "North Macedonia", CountryCode = "MK" },
                    new CountryMaster { CountryID = 131, CountryName = "Norway", CountryCode = "NO" },
                    new CountryMaster { CountryID = 132, CountryName = "Oman", CountryCode = "OM" },
                    new CountryMaster { CountryID = 133, CountryName = "Pakistan", CountryCode = "PK" },
                    new CountryMaster { CountryID = 134, CountryName = "Palau", CountryCode = "PW" },
                    new CountryMaster { CountryID = 135, CountryName = "Palestine", CountryCode = "PS" },
                    new CountryMaster { CountryID = 136, CountryName = "Panama", CountryCode = "PA" },
                    new CountryMaster { CountryID = 137, CountryName = "Papua New Guinea", CountryCode = "PG" },
                    new CountryMaster { CountryID = 138, CountryName = "Paraguay", CountryCode = "PY" },
                    new CountryMaster { CountryID = 139, CountryName = "Peru", CountryCode = "PE" },
                    new CountryMaster { CountryID = 140, CountryName = "Philippines", CountryCode = "PH" },
                    new CountryMaster { CountryID = 141, CountryName = "Poland", CountryCode = "PL" },
                    new CountryMaster { CountryID = 142, CountryName = "Portugal", CountryCode = "PT" },
                    new CountryMaster { CountryID = 143, CountryName = "Qatar", CountryCode = "QA" },
                    new CountryMaster { CountryID = 144, CountryName = "Romania", CountryCode = "RO" },
                    new CountryMaster { CountryID = 145, CountryName = "Russia", CountryCode = "RU" },
                    new CountryMaster { CountryID = 146, CountryName = "Rwanda", CountryCode = "RW" },
                    new CountryMaster { CountryID = 147, CountryName = "Saint Kitts and Nevis", CountryCode = "KN" },
                    new CountryMaster { CountryID = 148, CountryName = "Saint Lucia", CountryCode = "LC" },
                    new CountryMaster { CountryID = 149, CountryName = "Saint Vincent and the Grenadines", CountryCode = "VC" },
                    new CountryMaster { CountryID = 150, CountryName = "Samoa", CountryCode = "WS" },
                    new CountryMaster { CountryID = 151, CountryName = "San Marino", CountryCode = "SM" },
                    new CountryMaster { CountryID = 152, CountryName = "Sao Tome and Principe", CountryCode = "ST" },
                    new CountryMaster { CountryID = 153, CountryName = "Saudi Arabia", CountryCode = "SA" },
                    new CountryMaster { CountryID = 154, CountryName = "Senegal", CountryCode = "SN" },
                    new CountryMaster { CountryID = 155, CountryName = "Serbia", CountryCode = "RS" },
                    new CountryMaster { CountryID = 156, CountryName = "Seychelles", CountryCode = "SC" },
                    new CountryMaster { CountryID = 157, CountryName = "Sierra Leone", CountryCode = "SL" },
                    new CountryMaster { CountryID = 158, CountryName = "Singapore", CountryCode = "SG" },
                    new CountryMaster { CountryID = 159, CountryName = "Slovakia", CountryCode = "SK" },
                    new CountryMaster { CountryID = 160, CountryName = "Slovenia", CountryCode = "SI" },
                    new CountryMaster { CountryID = 161, CountryName = "Solomon Islands", CountryCode = "SB" },
                    new CountryMaster { CountryID = 162, CountryName = "Somalia", CountryCode = "SO" },
                    new CountryMaster { CountryID = 163, CountryName = "South Africa", CountryCode = "ZA" },
                    new CountryMaster { CountryID = 164, CountryName = "South Sudan", CountryCode = "SS" },
                    new CountryMaster { CountryID = 165, CountryName = "Spain", CountryCode = "ES" },
                    new CountryMaster { CountryID = 166, CountryName = "Sri Lanka", CountryCode = "LK" },
                    new CountryMaster { CountryID = 167, CountryName = "Sudan", CountryCode = "SD" },
                    new CountryMaster { CountryID = 168, CountryName = "Suriname", CountryCode = "SR" },
                    new CountryMaster { CountryID = 169, CountryName = "Sweden", CountryCode = "SE" },
                    new CountryMaster { CountryID = 170, CountryName = "Switzerland", CountryCode = "CH" },
                    new CountryMaster { CountryID = 171, CountryName = "Syria", CountryCode = "SY" },
                    new CountryMaster { CountryID = 172, CountryName = "Taiwan", CountryCode = "TW" },
                    new CountryMaster { CountryID = 173, CountryName = "Tajikistan", CountryCode = "TJ" },
                    new CountryMaster { CountryID = 174, CountryName = "Tanzania", CountryCode = "TZ" },
                    new CountryMaster { CountryID = 175, CountryName = "Thailand", CountryCode = "TH" },
                    new CountryMaster { CountryID = 176, CountryName = "Timor-Leste", CountryCode = "TL" },
                    new CountryMaster { CountryID = 177, CountryName = "Togo", CountryCode = "TG" },
                    new CountryMaster { CountryID = 178, CountryName = "Tonga", CountryCode = "TO" },
                    new CountryMaster { CountryID = 179, CountryName = "Trinidad and Tobago", CountryCode = "TT" },
                    new CountryMaster { CountryID = 180, CountryName = "Tunisia", CountryCode = "TN" },
                    new CountryMaster { CountryID = 181, CountryName = "Turkey", CountryCode = "TR" },
                    new CountryMaster { CountryID = 182, CountryName = "Turkmenistan", CountryCode = "TM" },
                    new CountryMaster { CountryID = 183, CountryName = "Tuvalu", CountryCode = "TV" },
                    new CountryMaster { CountryID = 184, CountryName = "Uganda", CountryCode = "UG" },
                    new CountryMaster { CountryID = 185, CountryName = "Ukraine", CountryCode = "UA" },
                    new CountryMaster { CountryID = 186, CountryName = "United Arab Emirates", CountryCode = "AE" },
                    new CountryMaster { CountryID = 187, CountryName = "United Kingdom", CountryCode = "GB" },
                    new CountryMaster { CountryID = 188, CountryName = "United States", CountryCode = "US" },
                    new CountryMaster { CountryID = 189, CountryName = "Uruguay", CountryCode = "UY" },
                    new CountryMaster { CountryID = 190, CountryName = "Uzbekistan", CountryCode = "UZ" },
                    new CountryMaster { CountryID = 191, CountryName = "Vanuatu", CountryCode = "VU" },
                    new CountryMaster { CountryID = 192, CountryName = "Vatican City", CountryCode = "VA" },
                    new CountryMaster { CountryID = 193, CountryName = "Venezuela", CountryCode = "VE" },
                    new CountryMaster { CountryID = 194, CountryName = "Vietnam", CountryCode = "VN" },
                    new CountryMaster { CountryID = 195, CountryName = "Yemen", CountryCode = "YE" },
                    new CountryMaster { CountryID = 196, CountryName = "Zambia", CountryCode = "ZM" },
                    new CountryMaster { CountryID = 197, CountryName = "Zimbabwe", CountryCode = "ZW" }
                );
            });
        }
    }
}
